################################################################
##
# assign2.cpp is the name of the source code.
# Type "make" or "make assign2" to compile the code.
##
# Type "make run" to run the code.
##
# Type "make clean" to remove the executable (and object files).
##
################################################################
CC=g++
CFLAGS=-Wall -g
assign2: assign2.cpp
	$(CC) -o assign2 $(CFLAGS) assign2.cpp
run: assign2
	./assign2
clean:
	$(RM) assign2